version: '3'
services:
  react-app:
    build:
      context: ./bzrp-front
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    volumes:
      - react-data:/app/data
    networks:
      - my-network

  python-app:
    build:
      context: ./BZRP-Backend-main
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    volumes:
      - python-data:/app
    networks:
      - my-network
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=bizza-rap3
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:

volumes:
  react-data:
  python-data:
  db-data:



